### ISSUE TITLE
sticker-label2dep

### ISSUE THREAD

**Issue by twuebi** [stickeritis/sticker#95]
It would be nice to be able to go from labels to dependencies as well. It would help in cases where training and prediction are done with an external tool.

**Comment by danieldk** [comment]
This existed at some point before the post-processing rules were added (though I don't think I added it to the repository). However, as we discussed last week, this gets pretty hairy, since for decoding we want to have the n-best results. Also, it requires string parsing of the labels, which is an easy way to introduce subtle bugs.

I was planning to make a Python binding at some point. Initially this would only expose loading a model + tagging. But at some later point, more the label encoding/decoding data structures could be exposed. This would allow one to use proper typed labels.

I will close this as wontfix, since I do not want to support string-parsing of best-n labels as a public interface.
